# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.17.2
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=0.0.1
maven_group=destinedtowander.oblivion
archives_base_name=oblivion

# Dependencies
emi_version=1.1.22+1.20.1
fabric_asm_version = v2.3
fabric_api_version=0.92.6+1.20.1
reach_entity_attributes_version=2.4.0
trinkets_version=3.7.2
lodestone_version = 1.20.1-1.6.2.3f-fabric
portinglib_version = 2.3.4+1.20.1
portinglib_modules = \
  accessors,\
  base,\
  blocks,\
  config,\
  core,\
  data,\
  entity,\
  extensions,\
  items,\
  lazy_registration,\
  model_generators,\
  models,\
  networking,\
  tags,\
  transfer,\
  tool_actions

#compatibility
blast_version = 1.13
pyp_version = 1.1.1
jade_version = 11.13.1+fabric
arsenal_version=0.1.5-1.20.1
ratatouille_version=1.0.9-1.20.1
satin_version = 1.14.0

#Enchancement
enchancement_version=1.20-26
cardinal_components_version=5.2.2
midnightlib_version=1.4.1-fabric
step_height_entity_attribute_version=25dabcdad7
tooltipfix_version=1.1.1-1.20
apoli_version=2.9.0
architectury_version=9.1.12
geckolib_version=1.20.1:4.3.1
sodium_version=mc1.20.1-0.5.11
spectrum_version=1.7.8
mod_menu_version=7.2.2
mixin_squared_version=0.1.2-beta.6